// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdY1nOZAKsUMjXB7WhRnp7bsD2v_FbWNE',
    appId: '1:731225787662:web:0274b730d37710cf6cdb5f',
    messagingSenderId: '731225787662',
    projectId: 'campus-connect-b3117',
    authDomain: 'campus-connect-b3117.firebaseapp.com',
    storageBucket: 'campus-connect-b3117.firebasestorage.app',
    measurementId: 'G-9YX2GCZMN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFf40OfB5ftZZvr-BOItuKNWPLVICCwV8',
    appId: '1:731225787662:android:156b0cd33c4626e26cdb5f',
    messagingSenderId: '731225787662',
    projectId: 'campus-connect-b3117',
    storageBucket: 'campus-connect-b3117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVq2at6FBkxfJpvnn285r_0NiqOAAfnzs',
    appId: '1:731225787662:ios:1a0bf3247656be806cdb5f',
    messagingSenderId: '731225787662',
    projectId: 'campus-connect-b3117',
    storageBucket: 'campus-connect-b3117.firebasestorage.app',
    iosBundleId: 'com.example.campusapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVq2at6FBkxfJpvnn285r_0NiqOAAfnzs',
    appId: '1:731225787662:ios:1a0bf3247656be806cdb5f',
    messagingSenderId: '731225787662',
    projectId: 'campus-connect-b3117',
    storageBucket: 'campus-connect-b3117.firebasestorage.app',
    iosBundleId: 'com.example.campusapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdY1nOZAKsUMjXB7WhRnp7bsD2v_FbWNE',
    appId: '1:731225787662:web:420ec44ac502bf8e6cdb5f',
    messagingSenderId: '731225787662',
    projectId: 'campus-connect-b3117',
    authDomain: 'campus-connect-b3117.firebaseapp.com',
    storageBucket: 'campus-connect-b3117.firebasestorage.app',
    measurementId: 'G-V1Q0055JXG',
  );
}
